### Import Pandas Library

In [1]:
import pandas as pd

### Reading the file

In [14]:
#read the csv file
df = pd.read_csv("StudentsPerformance.csv")
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [15]:
# display the first 10 rows of the csv file
df.head(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
9,female,group B,high school,free/reduced,none,38,60,50

In [16]:
#display the last 10 rows of the csv file
df.tail(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
990,male,group E,high school,free/reduced,completed,86,81,75
991,female,group B,some high school,standard,completed,65,82,78
992,female,group D,associate's degree,free/reduced,none,55,76,76
993,female,group D,bachelor's degree,free/reduced,none,62,72,74
994,male,group A,high school,standard,none,63,63,62
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [17]:
#display the column values in csv file
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [18]:
#display specific column in csv file 
df.loc[:, 'gender']

0      female
1      female
2      female
3        male
4        male
        ...
995    female
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: object

In [19]:
#display specific multiple columns in csv file
displayColumns = ['gender', 'reading score', 'writing score']
df.loc[:, displayColumns]

     gender  reading score  writing score
0    female             72             74
1    female             90             88
2    female             95             93
3      male             57             44
4      male             78             75
..      ...            ...            ...
995  female             99             95
996    male             55             55
997  female             71             65
998  female             78             77
999  female             86             86

[1000 rows x 3 columns]

In [20]:
#display specific rows along with specific columns in csv file
df.loc[7:24, displayColumns]

    gender  reading score  writing score
7     male             43             39
8     male             64             67
9   female             60             50
10    male             54             52
11    male             52             43
12  female             81             73
13    male             72             70
14  female             53             58
15  female             75             78
16    male             89             86
17  female             32             28
18    male             42             46
19  female             58             61
20    male             69             63
21  female             75             70
22    male             54             53
23  female             73             73
24    male             71             80

In [21]:
#accessing columns through the index method (iloc) in csv file

#first we figure out the column index
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [22]:
#index starts from 0, therefore [gender = 0, race/ethnicity = 1, parental level of education = 2... writing score = 7]
df.iloc[:, 0:2]

     gender race/ethnicity
0    female        group B
1    female        group C
2    female        group B
3      male        group A
4      male        group C
..      ...            ...
995  female        group E
996    male        group C
997  female        group C
998  female        group D
999  female        group D

[1000 rows x 2 columns]

In [23]:
#accessing specific rows and columns using iloc method in csv file
df.iloc[4:16, 2:-2]

,parental level of education,lunch,test preparation course,math score
4,some college,standard,none,76
5,associate's degree,standard,none,71
6,some college,standard,completed,88
7,some college,free/reduced,none,40
8,high school,free/reduced,completed,64
9,high school,free/reduced,none,38
10,associate's degree,standard,none,58
11,associate's degree,standard,none,40
12,high school,standard,none,65
13,some college,standard,completed,78
14,master's degree,standard,none,50
15,some high school,standard,none,69

### Accessing specific data from the file

In [24]:
#select any one particular column in csv file
df['gender']

0      female
1      female
2      female
3        male
4        male
        ...
995    female
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: object

In [26]:
#select any number of columns in csv file
df[displayColumns]

     gender  reading score  writing score
0    female             72             74
1    female             90             88
2    female             95             93
3      male             57             44
4      male             78             75
..      ...            ...            ...
995  female             99             95
996    male             55             55
997  female             71             65
998  female             78             77
999  female             86             86

[1000 rows x 3 columns]

In [27]:
#select the rows to display in csv file
df[displayColumns][15:30]

    gender  reading score  writing score
15  female             75             78
16    male             89             86
17  female             32             28
18    male             42             46
19  female             58             61
20    male             69             63
21  female             75             70
22    male             54             53
23  female             73             73
24    male             71             80
25    male             74             72
26    male             54             55
27  female             69             75
28    male             70             65
29  female             70             75

In [31]:
#select any particular row to display in csv file
df[displayColumns][4:5]

  gender  reading score  writing score
4   male             78             75

In [32]:
#select row to display in csv file
df.iloc[4]

gender                                 male
race/ethnicity                      group C
parental level of education    some college
lunch                              standard
test preparation course                none
math score                               76
reading score                            78
writing score                            75
Name: 4, dtype: object

In [33]:
#select rows to display in csv file
df.iloc[5:10]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
9,female,group B,high school,free/reduced,none,38,60,50

In [34]:
#selet a specific value in csv file
df.iloc[5, 1]

'group B'

In [35]:
#iterate individual rows in csv file
for index, rows in df.iterrows():
    print(index, rows)

0 gender                                    female
race/ethnicity                           group B
parental level of education    bachelor's degree
lunch                                   standard
test preparation course                     none
math score                                    72
reading score                                 72
writing score                                 74
Name: 0, dtype: object
1 gender                               female
race/ethnicity                      group C
parental level of education    some college
lunch                              standard
test preparation course           completed
math score                               69
reading score                            90
writing score                            88
Name: 1, dtype: object
2 gender                                  female
race/ethnicity                         group B
parental level of education    master's degree
lunch                                 standard
test preparation course                   none
math score                                  90
reading score                               95
writing score                               93
Name: 2, dtype: object
3 gender                                       male
race/ethnicity                            group A
parental level of education    associate's degree
lunch                                free/reduced
test preparation course                      none
math score                                     47
reading score                                  57
writing score                                  44
Name: 3, dtype: object
4 gender                                 male
race/ethnicity                      group C
parental level of education    some college
lunch                              standard
test preparation course                none
math score                               76
reading score                            78
writing score                            75
Name: 4, dtype: object
5 gender                                     female
race/ethnicity                            group B
parental level of education    associate's degree
lunch                                    standard
test preparation course                      none
math score                                     71
reading score                                  83
writing score                                  78
Name: 5, dtype: object
6 gender                               female
race/ethnicity                      group B
parental level of education    some college
lunch                              standard
test preparation course           completed
math score                               88
reading score                            95
writing score                            92
Name: 6, dtype: object
7 gender                                 male
race/ethnicity                      group B
parental level of education    some college
lunch                          free/reduced
test preparation course                none
math score                               40
reading score                            43
writing score                            39
Name: 7, dtype: object
8 gender                                 male
race/ethnicity                      group D
parental level of education     high school
lunch                          free/reduced
test preparation course           completed
math score                               64
reading score                            64
writing score                            67
Name: 8, dtype: object
9 gender                               female
race/ethnicity                      group B
parental level of education     high school
lunch                          free/reduced
test preparation course                none
math score                               38
reading score                            60
writing score                            50
Name: 9, dtype: object
10 gender                                       male
race/ethnicity                            group C
parental level of education    associate's degree
lunch                                    standard
test preparation course                      none
math score                                     58
reading score                                  54
writing score                                  52
Name: 10, dtype: object
11 gender                                       male
race/ethnicity                            group D
parental level of education    associate's degree
lunch                                    standard
test preparation course                      none
math score                                     40
reading score                                  52
writing score                                  43
Name: 11, dtype: object
12 gender                              female
race/ethnicity                     group B
parental level of education    high school
lunch                             standard
test preparation course               none
math score                              65
reading score                           81
writing score                           73
Name: 12, dtype: object
13 gender                                 male
race/ethnicity                      group A
parental level of education    some college
lunch                              standard
test preparation course           completed
math score                               78
reading score                            72
writing score                            70
Name: 13, dtype: object
14 gender                                  female
race/ethnicity                         group A
parental level of education    master's degree
lunch                                 standard
test preparation course                   none
math score                                  50
reading score                               53
writing score                               58
Name: 14, dtype: object
15 gender                                   female
race/ethnicity                          group C
parental level of education    some high school
lunch                                  standard
test preparation course                    none
math score                                   69
reading score                                75
writing score                                78
Name: 15, dtype: object
16 gender                                male
race/ethnicity                     group C
parental level of education    high school
lunch                             standard
test preparation course               none
math score                              88
reading score                           89
writing score                           86
Name: 16, dtype: object
17 gender                                   female
race/ethnicity                          group B
parental level of education    some high school
lunch                              free/reduced
test preparation course                    none
math score                                   18
reading score                                32
writing score                                28
Name: 17, dtype: object
18 gender                                    male
race/ethnicity                         group C
parental level of education    master's degree
lunch                             free/reduced
test preparation course              completed
math score                                  46
reading score                               42
writing score                               46
Name: 18, dtype: object
19 gender                                     female
race/ethnicity                            group C
parental level of education    associate's degree
lunch                                free/reduced
test preparation course                      none
math score                                     54
reading score                                  58
writing score                                  61
Name: 19, dtype: object
20 gender                                male
race/ethnicity                     group D
parental level of education    high school
lunch                             standard
test preparation course               none
math score                              66
reading score                           69
writing score                           63
Name: 20, dtype: object
21 gender                               female
race/ethnicity                      group B
parental level of education    some college
lunch                          free/reduced
test preparation course           completed
math score                               65
reading score                            75
writing score                            70
Name: 21, dtype: object
22 gender                                 male
race/ethnicity                      group D
parental level of education    some college
lunch                              standard
test preparation course                none
math score                               44
reading score                            54
writing score                            53
Name: 22, dtype: object
23 gender                                   female
race/ethnicity                          group C
parental level of education    some high school
lunch                                  standard
test preparation course                    none
math score                                   69
reading score                                73
writing score                                73
Name: 23, dtype: object
24 gender                                      male
race/ethnicity                           group D
parental level of education    bachelor's degree
lunch                               free/reduced
test preparation course                completed
math score                                    74
reading score                                 71
writing score                                 80
Name: 24, dtype: object
25 gender                                    male
race/ethnicity                         group A
parental level of education    master's degree
lunch                             free/reduced
test preparation course                   none
math score                                  73
reading score                               74
writing score                               72
Name: 25, dtype: object
26 gender                                 male
race/ethnicity                      group B
parental level of education    some college
lunch                              standard
test preparation course                none
math score                               69
reading score                            54
writing score                            55
Name: 26, dtype: object
27 gender                                    female
race/ethnicity                           group C
parental level of education    bachelor's degree
lunch                                   standard
test preparation course                     none
math score                                    67
reading score                                 69
writing score                                 75
Name: 27, dtype: object
28 gender                                male
race/ethnicity                     group C
parental level of education    high school
lunch                             standard
test preparation course               none
math score                              70
reading score                           70
writing score                           65
Name: 28, dtype: object
29 gender                                  female
race/ethnicity                         group D
parental level of education    master's degree
lunch                                 standard
test preparation course                   none
math score                                  62
reading score                               70
writing score                               75
Name: 29, dtype: object
30 gender                               female
race/ethnicity                      group D
parental level of education    some college
lunch                              standard
test preparation course                none
math score                               69
reading score                            74
writing score                            74
Name: 30, dtype: object
31 gender                               female
race/ethnicity                      group B
parental level of education    some college
lunch                              standard
test preparation course                none
math score                               63
reading score                            65
writing score                            61
Name: 31, dtype: object
32 gender                                  female
race/ethnicity                         group E
parental level of education    master's degree
lunch                             free/reduced
test preparation course                   none
math score                                  56
reading score                               72
writing score                               65
Name: 32, dtype: object
33 gender                                 male
race/ethnicity                      group D
parental level of education    some college
lunch                              standard
test preparation course                none
math score                               40
reading score                            42
writing score                            38
Name: 33, dtype: object
34 gender                                 male
race/ethnicity                      group E
parental level of education    some college
lunch                              standard
test preparation course                none
math score                               97
reading score                            87
writing score                            82
Name: 34, dtype: object
35 gender                                       male
race/ethnicity                            group E
parental level of education    associate's degree
lunch                                    standard
test preparation course                 completed
math score                                     81
reading score                                  81
writing score                                  79
Name: 35, dtype: object
36 gender                                     female
race/ethnicity                            group D
parental level of education    associate's degree
lunch                                    standard
test preparation course                      none
math score                                     74
reading score                                  81
writing score                                  83
Name: 36, dtype: object
37 gender                                   female
race/ethnicity                          group D
parental level of education    some high school
lunch                              free/reduced
test preparation course                    none
math score                                   50
reading score                                64
writing score                                59
Name: 37, dtype: object
38 gender                                     female
race/ethnicity                            group D
parental level of education    associate's degree
lunch                                free/reduced
test preparation course                 completed
math score                                     75
reading score                                  90
writing score                                  88
Name: 38, dtype: object
39 gender                                       male
race/ethnicity                            group B
parental level of education    associate's degree
lunch                                free/reduced
test preparation course                      none
math score                                     57
reading score                                  56
writing score                                  57
Name: 39, dtype: object
40 gender                                       male
race/ethnicity                            group C
parental level of education    associate's degree
lunch                                free/reduced
test preparation course                      none
math score                                     55
reading score                                  61
writing score                                  54
Name: 40, dtype: object
41 gender                                     female
race/ethnicity                            group C
parental level of education    associate's degree
lunch                                    standard
test preparation course                      none
math score                                     58
reading score                                  73
writing score                                  68
Name: 41, dtype: object
42 gender                                     female
race/ethnicity                            group B
parental level of education    associate's degree
lunch                                    standard
test preparation course                      none
math score                                     53
reading score                                  58
writing score                                  65
Name: 42, dtype: object
43 gender                                 male
race/ethnicity                      group B
parental level of education    some college
lunch                          free/reduced
test preparation course           completed
math score                               59
reading score                            65
writing score                            66
Name: 43, dtype: object
44 gender                                     female
race/ethnicity                            group E
parental level of education    associate's degree
lunch                                free/reduced
test preparation course                      none
math score                                     50
reading score                                  56
writing score                                  54
Name: 44, dtype: object
45 gender                                       male
race/ethnicity                            group B
parental level of education    associate's degree
lunch                                    standard
test preparation course                      none
math score                                     65
reading score                                  54
writing score                                  57
Name: 45, dtype: object
46 gender                                     female
race/ethnicity                            group A
parental level of education    associate's degree
lunch                                    standard
test preparation course                 completed
math score                                     55
reading score                                  65
writing score                                  62
Name: 46, dtype: object
47 gender                              female
race/ethnicity                     group C
parental level of education    high school
lunch                             standard
test preparation course               none
math score                              66
reading score                           71
writing score                           76
Name: 47, dtype: object
48 gender                                     female
race/ethnicity                            group D
parental level of education    associate's degree
lunch                                free/reduced
test preparation course                 completed
math score                                     57
reading score                                  74
writing score                                  76
Name: 48, dtype: object
49 gender                                male
race/ethnicity                     group C
parental level of education    high school
lunch                             standard
test preparation course          completed
math score                              82
reading score                           84

276 gender                                   female
race/ethnicity                          group C
parental level of education    some high school
lunch                                  standard
test preparation course               completed
math score                                   85
reading score                                92
writing score                                93
Name: 276, dtype: object
277 gender                              female
race/ethnicity                     group E
parental level of education    high school
lunch                             standard
test preparation course          completed
math score                              59
reading score                           63
writing score                           75
Name: 277, dtype: object
278 gender                                   female
race/ethnicity                          group C
parental level of education    some high school
lunch                              free/reduced
test preparation course                    none
math score                                   65
reading score                                86
writing score                                80
Name: 278, dtype: object
279 gender                                      male
race/ethnicity                           group B
parental level of education    bachelor's degree
lunch                               free/reduced
test preparation course                     none
math score                                    73
reading score                                 56
writing score                                 57
Name: 279, dtype: object
280 gender                                male
race/ethnicity                     group D
parental level of education    high school
lunch                             standard
test preparation course               none
math score                              53
reading score                           52
writing score                           42
Name: 280, dtype: object
281 gender                                male
race/ethnicity                     group D
parental level of education    high school
lunch                             standard
test preparation course               none
math score                              45
reading score                           48
writing score                           46
Name: 281, dtype: object
282 gender                                    female
race/ethnicity                           group D
parental level of education    bachelor's degree
lunch                               free/reduced
test preparation course                     none
math score                                    73
reading score                                 79
writing score                                 84
Name: 282, dtype: object
283 gender                               female
race/ethnicity                      group D
parental level of education    some college
lunch                          free/reduced
test preparation course           completed
math score                               70
reading score                            78
writing score                            78
Name: 283, dtype: object
284 gender                                   female
race/ethnicity                          group B
parental level of education    some high school
lunch                                  standard
test preparation course                    none
math score                                   37
reading score                                46
writing score                                46
Name: 284, dtype: object
285 gender                                       male
race/ethnicity                            group B
parental level of education    associate's degree
lunch                                    standard
test preparation course                 completed
math score                                     81
reading score                                  82
writing score                                  82
Name: 285, dtype: object
286 gender                                       male
race/ethnicity                            group E
parental level of education    associate's degree
lunch                                    standard
test preparation course                 completed
math score                                     97
reading score                                  82
writing score                                  88
Name: 286, dtype: object
287 gender                                   female
race/ethnicity                          group B
parental level of education    some high school
lunch                                  standard
test preparation course                    none
math score                                   67
reading score                                89
writing score                                82
Name: 287, dtype: object
288 gender                                      male
race/ethnicity                           group B
parental level of education    bachelor's degree
lunch                               free/reduced
test preparation course                     none
math score                                    88
reading score                                 75
writing score                                 76
Name: 288, dtype: object
289 gender                                     male
race/ethnicity                          group E
parental level of education    some high school
lunch                                  standard
test preparation course               completed
math score                                   77
reading score                                76
writing score                                77
Name: 289, dtype: object
290 gender                                       male
race/ethnicity                            group C
parental level of education    associate's degree
lunch                                    standard
test preparation course                      none
math score                                     76
reading score                                  70
writing score                                  68
Name: 290, dtype: object
291 gender                                     male
race/ethnicity                          group D
parental level of education    some high school
lunch                                  standard
test preparation course                    none
math score                                   86
reading score                                73
writing score                                70
Name: 291, dtype: object
292 gender                                     male
race/ethnicity                          group C
parental level of education    some high school
lunch                                  standard
test preparation course               completed
math score                                   63
reading score                                60
writing score                                57
Name: 292, dtype: object
293 gender                                    female
race/ethnicity                           group E
parental level of education    bachelor's degree
lunch                                   standard
test preparation course                     none
math score                                    65
reading score                                 73
writing score                                 75
Name: 293, dtype: object
294 gender                                 male
race/ethnicity                      group D
parental level of education     high school
lunch                          free/reduced
test preparation course           completed
math score                               78
reading score                            77
writing score                            80
Name: 294, dtype: object
295 gender                                       male
race/ethnicity                            group B
parental level of education    associate's degree
lunch                                free/reduced
test preparation course                      none
math score                                     67
reading score                                  62
writing score                                  60
Name: 295, dtype: object
296 gender                                     male
race/ethnicity                          group A
parental level of education    some high school
lunch                                  standard
test preparation course               completed
math score                                   46
reading score                                41
writing score                                43
Name: 296, dtype: object
297 gender                                       male
race/ethnicity                            group E
parental level of education    associate's degree
lunch                                    standard
test preparation course                 completed
math score                                     71
reading score                                  74
writing score                                  68
Name: 297, dtype: object
298 gender                                 male
race/ethnicity                      group C
parental level of education     high school
lunch                          free/reduced
test preparation course           completed
math score                               40
reading score                            46
writing score                            50
Name: 298, dtype: object
299 gender                                       male
race/ethnicity                            group D
parental level of education    associate's degree
lunch                                free/reduced
test preparation course                      none
math score                                     90
reading score                                  87
writing score                                  75
Name: 299, dtype: object
300 gender                                 male
race/ethnicity                      group A
parental level of education    some college
lunch                          free/reduced
test preparation course           completed
math score                               81
reading score                            78
writing score                            81
Name: 300, dtype: object
301 gender                                     male
race/ethnicity                          group D
parental level of education    some high school
lunch                              free/reduced
test preparation course                    none
math score                                   56
reading score                                54
writing score                                52
Name: 301, dtype: object
302 gender                                     female
race/ethnicity                            group C
parental level of education    associate's degree
lunch                                    standard
test preparation course                 completed
math score                                     67
reading score                                  84
writing score                                  81
Name: 302, dtype: object
303 gender                                       male
race/ethnicity                            group B
parental level of education    associate's degree
lunch                                    standard
test preparation course                      none
math score                                     80
reading score                                  76
writing score                                  64
Name: 303, dtype: object
304 gender                                     female
race/ethnicity                            group C
parental level of education    associate's degree
lunch                                    standard
test preparation course                 completed
math score                                     74
reading score                                  75
writing score                                  83
Name: 304, dtype: object
305 gender                                 male
race/ethnicity                      group A
parental level of education    some college
lunch                              standard
test preparation course                none
math score                               69
reading score                            67
writing score                            69
Name: 305, dtype: object
306 gender                                 male
race/ethnicity                      group E
parental level of education    some college
lunch                              standard
test preparation course           completed
math score                               99
reading score                            87
writing score                            81
Name: 306, dtype: object
307 gender                                     male
race/ethnicity                          group C
parental level of education    some high school
lunch                                  standard
test preparation course                    none
math score                                   51
reading score                                52
writing score                                44
Name: 307, dtype: object
308 gender                                     female
race/ethnicity                            group B
parental level of education    associate's degree
lunch                                free/reduced
test preparation course                      none
math score                                     53
reading score                                  71
writing score                                  67
Name: 308, dtype: object
309 gender                               female
race/ethnicity                      group D
parental level of education     high school
lunch                          free/reduced
test preparation course                none
math score                               49
reading score                            57
writing score                            52
Name: 309, dtype: object
310 gender                                     female
race/ethnicity                            group B
parental level of education    associate's degree
lunch                                    standard
test preparation course                      none
math score                                     73
reading score                                  76
writing score                                  80
Name: 310, dtype: object
311 gender                                      male
race/ethnicity                           group B
parental level of education    bachelor's degree
lunch                                   standard
test preparation course                     none
math score                                    66
reading score                                 60
writing score                                 57
Name: 311, dtype: object
312 gender                                      male
race/ethnicity                           group D
parental level of education    bachelor's degree
lunch                                   standard
test preparation course                completed
math score                                    67
reading score                                 61
writing score                                 68
Name: 312, dtype: object
313 gender                                     female
race/ethnicity                            group C
parental level of education    associate's degree
lunch                                free/reduced
test preparation course                 completed
math score                                     68
reading score                                  67
writing score                                  69
Name: 313, dtype: object
314 gender                                    female
race/ethnicity                           group C
parental level of education    bachelor's degree
lunch                                   standard
test preparation course                completed
math score                                    59
reading score                                 64
writing score                                 75
Name: 314, dtype: object
315 gender                                male
race/ethnicity                     group C
parental level of education    high school
lunch                             standard
test preparation course               none
math score                              71
reading score                           66
writing score                           65
Name: 315, dtype: object
316 gender                                  female
race/ethnicity                         group D
parental level of education    master's degree
lunch                                 standard
test preparation course              completed
math score                                  77
reading score                               82
writing score                               91
Name: 316, dtype: object
317 gender                                       male
race/ethnicity                            group C
parental level of education    associate's degree
lunch                                    standard
test preparation course                      none
math score                                     83
reading score                                  72
writing score                                  78
Name: 317, dtype: object
318 gender                                      male
race/ethnicity                           group B
parental level of education    bachelor's degree
lunch                                   standard
test preparation course                     none
math score                                    63
reading score                                 71
writing score                                 69
Name: 318, dtype: object
319 gender                                     female
race/ethnicity                            group D
parental level of education    associate's degree
lunch                                free/reduced
test preparation course                      none
math score                                     56
reading score                                  65
writing score                                  63
Name: 319, dtype: object
320 gender                               female
race/ethnicity                      group C
parental level of education     high school
lunch                          free/reduced
test preparation course           completed
math score                               67
reading score                            79
writing score                            84
Name: 320, dtype: object
321 gender                              female
race/ethnicity                     group E
parental level of education    high school
lunch                             standard
test preparation course               none
math score                              75
reading score                           86
writing score                           79
Name: 321, dtype: object
322 gender                               female
race/ethnicity                      group C
parental level of education    some college
lunch                              standard
test preparation course                none
math score                               71
reading score                            81
writing score                            80
Name: 322, dtype: object
323 gender                                   female
race/ethnicity                          group C
parental level of education    some high school
lunch                              free/reduced
test preparation course                    none
math score                                   43
reading score                                53
writing score                                53
Name: 323, dtype: object
324 gender                               female
race/ethnicity                      group C
parental level of education     high school
lunch                          free/reduced
test preparation course                none
math score                               41
reading score                            46
writing score                            43
Name: 324, dtype: object

542 gender                                     female
race/ethnicity                            group C
parental level of education    associate's degree
lunch                                    standard
test preparation course                      none
math score                                     81
reading score                                  77
writing score                                  79
Name: 542, dtype: object
543 gender                                     female
race/ethnicity                            group D
parental level of education    associate's degree
lunch                                    standard
test preparation course                      none
math score                                     82
reading score                                  95
writing score                                  89
Name: 543, dtype: object
544 gender                                  female
race/ethnicity                         group D
parental level of education    master's degree
lunch                                 standard
test preparation course                   none
math score                                  64
reading score                               63
writing score                               66
Name: 544, dtype: object
545 gender                                     male
race/ethnicity                          group E
parental level of education    some high school
lunch                              free/reduced
test preparation course               completed
math score                                   78
reading score                                83
writing score                                80
Name: 545, dtype: object
546 gender                                   female
race/ethnicity                          group A
parental level of education    some high school
lunch                                  standard
test preparation course               completed
math score                                   92
reading score                               100
writing score                                97
Name: 546, dtype: object
547 gender                                male
race/ethnicity                     group C
parental level of education    high school
lunch                             standard
test preparation course          completed
math score                              72
reading score                           67
writing score                           64
Name: 547, dtype: object
548 gender                               female
race/ethnicity                      group C
parental level of education     high school
lunch                          free/reduced
test preparation course                none
math score                               62
reading score                            67
writing score                            64
Name: 548, dtype: object
549 gender                                    male
race/ethnicity                         group C
parental level of education    master's degree
lunch                                 standard
test preparation course                   none
math score                                  79
reading score                               72
writing score                               69
Name: 549, dtype: object
550 gender                                     male
race/ethnicity                          group C
parental level of education    some high school
lunch                              free/reduced
test preparation course                    none
math score                                   79
reading score                                76
writing score                                65
Name: 550, dtype: object
551 gender                                      male
race/ethnicity                           group B
parental level of education    bachelor's degree
lunch                               free/reduced
test preparation course                completed
math score                                    87
reading score                                 90
writing score                                 88
Name: 551, dtype: object
552 gender                                     female
race/ethnicity                            group B
parental level of education    associate's degree
lunch                                    standard
test preparation course                      none
math score                                     40
reading score                                  48
writing score                                  50
Name: 552, dtype: object
553 gender                                 male
race/ethnicity                      group D
parental level of education    some college
lunch                          free/reduced
test preparation course                none
math score                               77
reading score                            62
writing score                            64
Name: 553, dtype: object
554 gender                                       male
race/ethnicity                            group E
parental level of education    associate's degree
lunch                                    standard
test preparation course                      none
math score                                     53
reading score                                  45
writing score                                  40
Name: 554, dtype: object
555 gender                               female
race/ethnicity                      group C
parental level of education    some college
lunch                          free/reduced
test preparation course                none
math score                               32
reading score                            39
writing score                            33
Name: 555, dtype: object
556 gender                                     female
race/ethnicity                            group C
parental level of education    associate's degree
lunch                                    standard
test preparation course                 completed
math score                                     55
reading score                                  72
writing score                                  79
Name: 556, dtype: object
557 gender                                    male
race/ethnicity                         group C
parental level of education    master's degree
lunch                             free/reduced
test preparation course                   none
math score                                  61
reading score                               67
writing score                               66
Name: 557, dtype: object
558 gender                                     female
race/ethnicity                            group B
parental level of education    associate's degree
lunch                                free/reduced
test preparation course                      none
math score                                     53
reading score                                  70
writing score                                  70
Name: 558, dtype: object
559 gender                                     male
race/ethnicity                          group D
parental level of education    some high school
lunch                                  standard
test preparation course                    none
math score                                   73
reading score                                66
writing score                                62
Name: 559, dtype: object
560 gender                               female
race/ethnicity                      group D
parental level of education    some college
lunch                              standard
test preparation course           completed
math score                               74
reading score                            75
writing score                            79
Name: 560, dtype: object
561 gender                               female
race/ethnicity                      group C
parental level of education    some college
lunch                              standard
test preparation course                none
math score                               63
reading score                            74
writing score                            74
Name: 561, dtype: object
562 gender                                      male
race/ethnicity                           group C
parental level of education    bachelor's degree
lunch                                   standard
test preparation course                completed
math score                                    96
reading score                                 90
writing score                                 92
Name: 562, dtype: object
563 gender                               female
race/ethnicity                      group D
parental level of education    some college
lunch                          free/reduced
test preparation course           completed
math score                               63
reading score                            80
writing score                            80
Name: 563, dtype: object
564 gender                                      male
race/ethnicity                           group B
parental level of education    bachelor's degree
lunch                               free/reduced
test preparation course                     none
math score                                    48
reading score                                 51
writing score                                 46
Name: 564, dtype: object
565 gender                                       male
race/ethnicity                            group B
parental level of education    associate's degree
lunch                                    standard
test preparation course                      none
math score                                     48
reading score                                  43
writing score                                  45
Name: 565, dtype: object
566 gender                                    female
race/ethnicity                           group E
parental level of education    bachelor's degree
lunch                               free/reduced
test preparation course                completed
math score                                    92
reading score                                100
writing score                                100
Name: 566, dtype: object
567 gender                                  female
race/ethnicity                         group D
parental level of education    master's degree
lunch                             free/reduced
test preparation course              completed
math score                                  61
reading score                               71
writing score                               78
Name: 567, dtype: object
568 gender                                 male
race/ethnicity                      group B
parental level of education     high school
lunch                          free/reduced
test preparation course                none
math score                               63
reading score                            48
writing score                            47
Name: 568, dtype: object
569 gender                                      male
race/ethnicity                           group D
parental level of education    bachelor's degree
lunch                               free/reduced
test preparation course                     none
math score                                    68
reading score                                 68
writing score                                 67
Name: 569, dtype: object
570 gender                                 male
race/ethnicity                      group B
parental level of education    some college
lunch                              standard
test preparation course           completed
math score                               71
reading score                            75
writing score                            70
Name: 570, dtype: object
571 gender                                      male
race/ethnicity                           group A
parental level of education    bachelor's degree
lunch                                   standard
test preparation course                     none
math score                                    91
reading score                                 96
writing score                                 92
Name: 571, dtype: object
572 gender                               female
race/ethnicity                      group C
parental level of education    some college
lunch                              standard
test preparation course                none
math score                               53
reading score                            62
writing score                            56
Name: 572, dtype: object
573 gender                               female
race/ethnicity                      group C
parental level of education     high school
lunch                          free/reduced
test preparation course           completed
math score                               50
reading score                            66
writing score                            64
Name: 573, dtype: object
574 gender                              female
race/ethnicity                     group E
parental level of education    high school
lunch                             standard
test preparation course               none
math score                              74
reading score                           81
writing score                           71
Name: 574, dtype: object
575 gender                                       male
race/ethnicity                            group A
parental level of education    associate's degree
lunch                                free/reduced
test preparation course                 completed
math score                                     40
reading score                                  55
writing score                                  53
Name: 575, dtype: object
576 gender                                 male
race/ethnicity                      group A
parental level of education    some college
lunch                              standard
test preparation course           completed
math score                               61
reading score                            51
writing score                            52
Name: 576, dtype: object
577 gender                              female
race/ethnicity                     group B
parental level of education    high school
lunch                             standard
test preparation course               none
math score                              81
reading score                           91
writing score                           89
Name: 577, dtype: object
578 gender                               female
race/ethnicity                      group B
parental level of education    some college
lunch                          free/reduced
test preparation course           completed
math score                               48
reading score                            56
writing score                            58
Name: 578, dtype: object
579 gender                                  female
race/ethnicity                         group D
parental level of education    master's degree
lunch                                 standard
test preparation course                   none
math score                                  53
reading score                               61
writing score                               68
Name: 579, dtype: object
580 gender                                   female
race/ethnicity                          group D
parental level of education    some high school
lunch                                  standard
test preparation course                    none
math score                                   81
reading score                                97
writing score                                96
Name: 580, dtype: object
581 gender                                   female
race/ethnicity                          group E
parental level of education    some high school
lunch                                  standard
test preparation course                    none
math score                                   77
reading score                                79
writing score                                80
Name: 581, dtype: object
582 gender                                    female
race/ethnicity                           group D
parental level of education    bachelor's degree
lunch                               free/reduced
test preparation course                     none
math score                                    63
reading score                                 73
writing score                                 78
Name: 582, dtype: object
583 gender                                     female
race/ethnicity                            group D
parental level of education    associate's degree
lunch                                    standard
test preparation course                 completed
math score                                     73
reading score                                  75
writing score                                  80
Name: 583, dtype: object
584 gender                               female
race/ethnicity                      group D
parental level of education    some college
lunch                              standard
test preparation course                none
math score                               69
reading score                            77
writing score                            77
Name: 584, dtype: object
585 gender                                     female
race/ethnicity                            group C
parental level of education    associate's degree
lunch                                    standard
test preparation course                      none
math score                                     65
reading score                                  76
writing score                                  76
Name: 585, dtype: object
586 gender                              female
race/ethnicity                     group A
parental level of education    high school
lunch                             standard
test preparation course               none
math score                              55
reading score                           73
writing score                           73
Name: 586, dtype: object
587 gender                                    female
race/ethnicity                           group C
parental level of education    bachelor's degree
lunch                               free/reduced
test preparation course                     none
math score                                    44
reading score                                 63
writing score                                 62
Name: 587, dtype: object
588 gender                               female
race/ethnicity                      group C
parental level of education    some college
lunch                              standard
test preparation course                none
math score                               54
reading score                            64
writing score                            65
Name: 588, dtype: object
589 gender                                   female
race/ethnicity                          group A
parental level of education    some high school
lunch                                  standard
test preparation course                    none
math score                                   48
reading score                                66
writing score                                65
Name: 589, dtype: object
590 gender                                 male
race/ethnicity                      group C
parental level of education    some college
lunch                          free/reduced
test preparation course                none
math score                               58
reading score                            57
writing score                            54
Name: 590, dtype: object
591 gender                                     male
race/ethnicity                          group A
parental level of education    some high school
lunch                                  standard

Name: 778, dtype: object
779 gender                                       male
race/ethnicity                            group E
parental level of education    associate's degree
lunch                                    standard
test preparation course                 completed
math score                                     94
reading score                                  85
writing score                                  82
Name: 779, dtype: object
780 gender                                     female
race/ethnicity                            group D
parental level of education    associate's degree
lunch                                free/reduced
test preparation course                      none
math score                                     46
reading score                                  56
writing score                                  57
Name: 780, dtype: object
781 gender                                  female
race/ethnicity                         group B
parental level of education    master's degree
lunch                                 standard
test preparation course                   none
math score                                  77
reading score                               90
writing score                               84
Name: 781, dtype: object
782 gender                               female
race/ethnicity                      group B
parental level of education     high school
lunch                          free/reduced
test preparation course           completed
math score                               76
reading score                            85
writing score                            82
Name: 782, dtype: object
783 gender                                     female
race/ethnicity                            group C
parental level of education    associate's degree
lunch                                    standard
test preparation course                 completed
math score                                     52
reading score                                  59
writing score                                  62
Name: 783, dtype: object
784 gender                                      male
race/ethnicity                           group C
parental level of education    bachelor's degree
lunch                                   standard
test preparation course                completed
math score                                    91
reading score                                 81
writing score                                 79
Name: 784, dtype: object
785 gender                                   female
race/ethnicity                          group B
parental level of education    some high school
lunch                                  standard
test preparation course               completed
math score                                   32
reading score                                51
writing score                                44
Name: 785, dtype: object
786 gender                                   female
race/ethnicity                          group E
parental level of education    some high school
lunch                              free/reduced
test preparation course                    none
math score                                   72
reading score                                79
writing score                                77
Name: 786, dtype: object
787 gender                               female
race/ethnicity                      group B
parental level of education    some college
lunch                              standard
test preparation course                none
math score                               19
reading score                            38
writing score                            32
Name: 787, dtype: object
788 gender                                       male
race/ethnicity                            group C
parental level of education    associate's degree
lunch                                free/reduced
test preparation course                      none
math score                                     68
reading score                                  65
writing score                                  61
Name: 788, dtype: object
789 gender                                  female
race/ethnicity                         group C
parental level of education    master's degree
lunch                             free/reduced
test preparation course                   none
math score                                  52
reading score                               65
writing score                               61
Name: 789, dtype: object
790 gender                              female
race/ethnicity                     group B
parental level of education    high school
lunch                             standard
test preparation course               none
math score                              48
reading score                           62
writing score                           60
Name: 790, dtype: object
791 gender                               female
race/ethnicity                      group D
parental level of education    some college
lunch                          free/reduced
test preparation course                none
math score                               60
reading score                            66
writing score                            70
Name: 791, dtype: object
792 gender                                 male
race/ethnicity                      group D
parental level of education     high school
lunch                          free/reduced
test preparation course                none
math score                               66
reading score                            74
writing score                            69
Name: 792, dtype: object
793 gender                                     male
race/ethnicity                          group E
parental level of education    some high school
lunch                                  standard
test preparation course               completed
math score                                   89
reading score                                84
writing score                                77
Name: 793, dtype: object
794 gender                              female
race/ethnicity                     group B
parental level of education    high school
lunch                             standard
test preparation course               none
math score                              42
reading score                           52
writing score                           51
Name: 794, dtype: object
795 gender                                     female
race/ethnicity                            group E
parental level of education    associate's degree
lunch                                free/reduced
test preparation course                 completed
math score                                     57
reading score                                  68
writing score                                  73
Name: 795, dtype: object
796 gender                                male
race/ethnicity                     group D
parental level of education    high school
lunch                             standard
test preparation course               none
math score                              70
reading score                           70
writing score                           70
Name: 796, dtype: object
797 gender                                     female
race/ethnicity                            group E
parental level of education    associate's degree
lunch                                free/reduced
test preparation course                      none
math score                                     70
reading score                                  84
writing score                                  81
Name: 797, dtype: object
798 gender                                 male
race/ethnicity                      group E
parental level of education    some college
lunch                              standard
test preparation course                none
math score                               69
reading score                            60
writing score                            54
Name: 798, dtype: object
799 gender                                     female
race/ethnicity                            group C
parental level of education    associate's degree
lunch                                    standard
test preparation course                      none
math score                                     52
reading score                                  55
writing score                                  57
Name: 799, dtype: object
800 gender                                     male
race/ethnicity                          group C
parental level of education    some high school
lunch                                  standard
test preparation course               completed
math score                                   67
reading score                                73
writing score                                68
Name: 800, dtype: object
801 gender                                     male
race/ethnicity                          group C
parental level of education    some high school
lunch                                  standard
test preparation course               completed
math score                                   76
reading score                                80
writing score                                73
Name: 801, dtype: object
802 gender                                     female
race/ethnicity                            group E
parental level of education    associate's degree
lunch                                    standard
test preparation course                      none
math score                                     87
reading score                                  94
writing score                                  95
Name: 802, dtype: object
803 gender                               female
race/ethnicity                      group B
parental level of education    some college
lunch                              standard
test preparation course                none
math score                               82
reading score                            85
writing score                            87
Name: 803, dtype: object
804 gender                               female
race/ethnicity                      group C
parental level of education    some college
lunch                              standard
test preparation course                none
math score                               73
reading score                            76
writing score                            78
Name: 804, dtype: object
805 gender                                 male
race/ethnicity                      group A
parental level of education    some college
lunch                          free/reduced
test preparation course                none
math score                               75
reading score                            81
writing score                            74
Name: 805, dtype: object
806 gender                               female
race/ethnicity                      group D
parental level of education    some college
lunch                          free/reduced
test preparation course                none
math score                               64
reading score                            74
writing score                            75
Name: 806, dtype: object
807 gender                               female
race/ethnicity                      group E
parental level of education     high school
lunch                          free/reduced
test preparation course                none
math score                               41
reading score                            45
writing score                            40
Name: 807, dtype: object
808 gender                                male
race/ethnicity                     group C
parental level of education    high school
lunch                             standard
test preparation course               none
math score                              90
reading score                           75
writing score                           69
Name: 808, dtype: object
809 gender                                      male
race/ethnicity                           group B
parental level of education    bachelor's degree
lunch                                   standard
test preparation course                     none
math score                                    59
reading score                                 54
writing score                                 51
Name: 809, dtype: object
810 gender                                     male
race/ethnicity                          group A
parental level of education    some high school
lunch                                  standard
test preparation course                    none
math score                                   51
reading score                                31
writing score                                36
Name: 810, dtype: object
811 gender                                 male
race/ethnicity                      group A
parental level of education     high school
lunch                          free/reduced
test preparation course                none
math score                               45
reading score                            47
writing score                            49
Name: 811, dtype: object
812 gender                                  female
race/ethnicity                         group C
parental level of education    master's degree
lunch                                 standard
test preparation course              completed
math score                                  54
reading score                               64
writing score                               67
Name: 812, dtype: object
813 gender                                     male
race/ethnicity                          group E
parental level of education    some high school
lunch                                  standard
test preparation course               completed
math score                                   87
reading score                                84
writing score                                76
Name: 813, dtype: object
814 gender                              female
race/ethnicity                     group C
parental level of education    high school
lunch                             standard
test preparation course               none
math score                              72
reading score                           80
writing score                           83
Name: 814, dtype: object
815 gender                                     male
race/ethnicity                          group B
parental level of education    some high school
lunch                                  standard
test preparation course               completed
math score                                   94
reading score                                86
writing score                                87
Name: 815, dtype: object
816 gender                                    female
race/ethnicity                           group A
parental level of education    bachelor's degree
lunch                                   standard
test preparation course                     none
math score                                    45
reading score                                 59
writing score                                 64
Name: 816, dtype: object
817 gender                                      male
race/ethnicity                           group D
parental level of education    bachelor's degree
lunch                               free/reduced
test preparation course                completed
math score                                    61
reading score                                 70
writing score                                 76
Name: 817, dtype: object
818 gender                               female
race/ethnicity                      group B
parental level of education     high school
lunch                          free/reduced
test preparation course                none
math score                               60
reading score                            72
writing score                            68
Name: 818, dtype: object
819 gender                                   female
race/ethnicity                          group C
parental level of education    some high school
lunch                                  standard
test preparation course                    none
math score                                   77
reading score                                91
writing score                                88
Name: 819, dtype: object
820 gender                                   female
race/ethnicity                          group A
parental level of education    some high school
lunch                                  standard
test preparation course               completed
math score                                   85
reading score                                90
writing score                                92
Name: 820, dtype: object
821 gender                                    female
race/ethnicity                           group D
parental level of education    bachelor's degree
lunch                               free/reduced
test preparation course                     none
math score                                    78
reading score                                 90
writing score                                 93
Name: 821, dtype: object
822 gender                                 male
race/ethnicity                      group E
parental level of education    some college
lunch                          free/reduced
test preparation course           completed
math score                               49
reading score                            52
writing score                            51
Name: 822, dtype: object
823 gender                               female
race/ethnicity                      group B
parental level of education     high school
lunch                          free/reduced
test preparation course                none
math score                               71
reading score                            87
writing score                            82
Name: 823, dtype: object
824 gender                                   female
race/ethnicity                          group C
parental level of education    some high school
lunch                              free/reduced
test preparation course                    none
math score                                   48
reading score                                58
writing score                                52
Name: 824, dtype: object
825 gender                                male
race/ethnicity                     group C
parental level of education    high school
lunch                             standard
test preparation course               none
math score                              62
reading score                           67
writing score                           58
Name: 825, dtype: object
826 gender                                     female
race/ethnicity                            group C
parental level of education    associate's degree
lunch                                free/reduced
test preparation course                 completed
math score                                     56
reading score                                  68
writing score                                  70
Name: 826, dtype: object
827 gender                                   female
race/ethnicity                          group C
parental level of education    some high school
lunch                                  standard
test preparation course                    none
math score                                   65
reading score                                69
writing score                                76
Name: 827, dtype: object
828 gender                                   female
race/ethnicity                          group D
parental level of education    some high school
lunch                              free/reduced
test preparation course               completed

In [36]:
#iterate individual rows through specified column in csv file
for index, rows in df.iterrows():
    print(index, rows['gender'])

0 female
1 female
2 female
3 male
4 male
5 female
6 female
7 male
8 male
9 female
10 male
11 male
12 female
13 male
14 female
15 female
16 male
17 female
18 male
19 female
20 male
21 female
22 male
23 female
24 male
25 male
26 male
27 female
28 male
29 female
30 female
31 female
32 female
33 male
34 male
35 male
36 female
37 female
38 female
39 male
40 male
41 female
42 female
43 male
44 female
45 male
46 female
47 female
48 female
49 male
50 male
51 male
52 male
53 male
54 female
55 female
56 female
57 male
58 male
59 female
60 male
61 male
62 male
63 female
64 female
65 male
66 male
67 female
68 male
69 female
70 female
71 male
72 female
73 male
74 male
75 male
76 male
77 male
78 female
79 female
80 female
81 male
82 male
83 male
84 male
85 female
86 female
87 female
88 female
89 female
90 female
91 male
92 male
93 male
94 female
95 male
96 male
97 female
98 female
99 female
100 male
101 male
102 female
103 male
104 male
105 female
106 female
107 male
108 female
109 female
110 female
111 male
112 male
113 female
114 female
115 male
116 female
117 female
118 female
119 female
120 female
121 male
122 female
123 male
124 male
125 female
126 male
127 male
128 male
129 female
130 male
131 male
132 male
133 female
134 male
135 male
136 male
137 male
138 female
139 male
140 female
141 female
142 female
143 male
144 male
145 female
146 male
147 male
148 female
149 male
150 male
151 male
152 female
153 male
154 male
155 female
156 female
157 male
158 female
159 male
160 male
161 female
162 male
163 male
164 female
165 female
166 male
167 female
168 female
169 female
170 male
171 male
172 female
173 female
174 female
175 female
176 female
177 female
178 female
179 female
180 male
181 female
182 female
183 female
184 male
185 male
186 male
187 male
188 male
189 female
190 female
191 male
192 female
193 male
194 female
195 male
196 male
197 male
198 female
199 female
200 female
201 female
202 male
203 female
204 male
205 male
206 male
207 male
208 female
209 female
210 male
211 male
212 female
213 male
214 male
215 male
216 female
217 female
218 male
219 male
220 female
221 male
222 female
223 male
224 female
225 female
226 female
227 male
228 male
229 female
230 male
231 male
232 female
233 male
234 male
235 male
236 male
237 female
238 male
239 male
240 male
241 female
242 female
243 male
244 male
245 male
246 male
247 female
248 female
249 male
250 male
251 female
252 female
253 male
254 male
255 female
256 female
257 male
258 female
259 female
260 female
261 male
262 female
263 female
264 male
265 male
266 female
267 female
268 female
269 female
270 male
271 male
272 female
273 female
274 male
275 male
276 female
277 female
278 female
279 male
280 male
281 male
282 female
283 female
284 female
285 male
286 male
287 female
288 male
289 male
290 male
291 male
292 male
293 female
294 male
295 male
296 male
297 male
298 male
299 male
300 male
301 male
302 female
303 male
304 female
305 male
306 male
307 male
308 female
309 female
310 female
311 male
312 male
313 female
314 female
315 male
316 female
317 male
318 male
319 female
320 female
321 female
322 female
323 female
324 female
325 female
326 male
327 male
328 male
329 female
330 male
331 male
332 male
333 male
334 female
335 female
336 male
337 male
338 female
339 female
340 male
341 female
342 female
343 male
344 male
345 female
346 male
347 female
348 male
349 male
350 female
351 male
352 female
353 female
354 female
355 female
356 male
357 female
358 male
359 female
360 female
361 male
362 female
363 female
364 male
365 male
366 male
367 male
368 female
369 female
370 male
371 female
372 male
373 female
374 female
375 male
376 female
377 female
378 female
379 male
380 female
381 male
382 male
383 female
384 female
385 female
386 female
387 female
388 female
389 male
390 male
391 female
392 male
393 male
394 female
395 male
396 female
397 female
398 male
399 male
400 female
401 male
402 female
403 female
404 female
405 female
406 male
407 female
408 female
409 male
410 female
411 male
412 male
413 male
414 female
415 male
416 male
417 male
418 male
419 male
420 female
421 female
422 female
423 female
424 male
425 female
426 male
427 male
428 male
429 male
430 male
431 female
432 male
433 female
434 male
435 male
436 male
437 male
438 male
439 male
440 female
441 female
442 female
443 female
444 male
445 female
446 male
447 male
448 male
449 male
450 female
451 female
452 female
453 male
454 female
455 male
456 female
457 male
458 female
459 male
460 male
461 male
462 female
463 female
464 male
465 female
466 female
467 male
468 female
469 male
470 female
471 female
472 female
473 female
474 female
475 female
476 male
477 male
478 female
479 male
480 male
481 female
482 male
483 male
484 female
485 male
486 male
487 female
488 male
489 male
490 female
491 female
492 female
493 female
494 female
495 male
496 female
497 female
498 female
499 male
500 female
501 female
502 male
503 female
504 female
505 female
506 male
507 male
508 male
509 female
510 male
511 male
512 male
513 female
514 female
515 female
516 female
517 female
518 female
519 female
520 male
521 female
522 male
523 male
524 male
525 male
526 male
527 female
528 female
529 female
530 female
531 female
532 male
533 female
534 male
535 female
536 male
537 female
538 male
539 male
540 male
541 male
542 female
543 female
544 female
545 male
546 female
547 male
548 female
549 male
550 male
551 male
552 female
553 male
554 male
555 female
556 female
557 male
558 female
559 male
560 female
561 female
562 male
563 female
564 male
565 male
566 female
567 female
568 male
569 male
570 male
571 male
572 female
573 female
574 female
575 male
576 male
577 female
578 female
579 female
580 female
581 female
582 female
583 female
584 female
585 female
586 female
587 female
588 female
589 female
590 male
591 male
592 male
593 female
594 female
595 female
596 male
597 male
598 female
599 female
600 female
601 female
602 female
603 male
604 male
605 male
606 female
607 female
608 female
609 female
610 male
611 female
612 male
613 female
614 female
615 female
616 female
617 male
618 male
619 male
620 female
621 male
622 male
623 male
624 female
625 male
626 male
627 male
628 male
629 female
630 male
631 male
632 female
633 female
634 male
635 male
636 female
637 female
638 male
639 female
640 male
641 female
642 female
643 female
644 male
645 female
646 female
647 female
648 female
649 female
650 male
651 female
652 female
653 female
654 female
655 female
656 male
657 male
658 female
659 male
660 male
661 male
662 female
663 female
664 male
665 female
666 female
667 female
668 male
669 male
670 female
671 male
672 female
673 female
674 female
675 female
676 female
677 female
678 male
679 male
680 female
681 male
682 male
683 female
684 male
685 female
686 male
687 male
688 male
689 male
690 female
691 female
692 female
693 female
694 female
695 female
696 female
697 female
698 female
699 male
700 female
701 female
702 male
703 female
704 female
705 male
706 male
707 male
708 male
709 female
710 male
711 female
712 female
713 male
714 female
715 female
716 male
717 female
718 female
719 male
720 female
721 male
722 female
723 male
724 male
725 male
726 female
727 male
728 female
729 male
730 female
731 male
732 female
733 male
734 female
735 male
736 male
737 female
738 male
739 male
740 male
741 female
742 female
743 female
744 male
745 male
746 male
747 male
748 female
749 male
750 male
751 male
752 male
753 female
754 male
755 female
756 male
757 male
758 female
759 male
760 female
761 female
762 male
763 female
764 male
765 female
766 female
767 male
768 female
769 male
770 male
771 male
772 female
773 female
774 male
775 female
776 female
777 female
778 female
779 male
780 female
781 female
782 female
783 female
784 male
785 female
786 female
787 female
788 male
789 female
790 female
791 female
792 male
793 male
794 female
795 female
796 male
797 female
798 male
799 female
800 male
801 male
802 female
803 female
804 female
805 male
806 female
807 female
808 male
809 male
810 male
811 male
812 female
813 male
814 female
815 male
816 female
817 male
818 female
819 female
820 female
821 female
822 male
823 female
824 female
825 male
826 female
827 female
828 female
829 male
830 female
831 female
832 male
833 female
834 male
835 female
836 male
837 female
838 male
839 female
840 female
841 male
842 female
843 male
844 female
845 male
846 male
847 male
848 female
849 male
850 male
851 female
852 female
853 male
854 male
855 female
856 male
857 female
858 male
859 male
860 female
861 female
862 male
863 female
864 male
865 male
866 male
867 male
868 male
869 male
870 male
871 female
872 male
873 male
874 female
875 male
876 male
877 male
878 female
879 female
880 male
881 female
882 female
883 male
884 female
885 female
886 female
887 male
888 female
889 male
890 female
891 female
892 female
893 male
894 female
895 female
896 male
897 female
898 male
899 female
900 male
901 female
902 female
903 female
904 female
905 male
906 male
907 female
908 female
909 male
910 male
911 female
912 female
913 female
914 female
915 female
916 male
917 female
918 female
919 male
920 male
921 female
922 male
923 female
924 male
925 male
926 male
927 female
928 male
929 female
930 male
931 male
932 male
933 male
934 male
935 male
936 male
937 female
938 male
939 male
940 male
941 female
942 male
943 male
944 female
945 female
946 male
947 female
948 male
949 female
950 male
951 female
952 female
953 male
954 female
955 male
956 male
957 female
958 female
959 male
960 female
961 female
962 female
963 female
964 male
965 female
966 male
967 male
968 female
969 female
970 female
971 male
972 female
973 female
974 female
975 female
976 male
977 male
978 male
979 female
980 female
981 male
982 male
983 female
984 female
985 male
986 female
987 male
988 female
989 female
990 male
991 female
992 female
993 female
994 male
995 female
996 male
997 female
998 female
999 female

In [39]:
#access using specific keyword in csv file
df.loc[df['test preparation course'] == "completed"]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
1,female,group C,some college,standard,completed,69,90,88
6,female,group B,some college,standard,completed,88,95,92
8,male,group D,high school,free/reduced,completed,64,64,67
13,male,group A,some college,standard,completed,78,72,70
18,male,group C,master's degree,free/reduced,completed,46,42,46
...,...,...,...,...,...,...,...,...
990,male,group E,high school,free/reduced,completed,86,81,75
991,female,group B,some high school,standard,completed,65,82,78
995,female,group E,master's degree,standard,completed,88,99,95
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77

In [40]:
#sort values in ascending order in a column in csv file
df.sort_values('writing score', ascending=True)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
59,female,group C,some high school,free/reduced,none,0,17,10
596,male,group B,high school,free/reduced,none,30,24,15
327,male,group A,some college,free/reduced,none,28,23,19
76,male,group E,some high school,standard,none,30,26,22
980,female,group B,high school,free/reduced,none,8,24,23
...,...,...,...,...,...,...,...,...
970,female,group D,bachelor's degree,standard,none,89,100,100
106,female,group D,master's degree,standard,none,87,100,100
957,female,group D,master's degree,standard,none,92,100,100
916,male,group E,bachelor's degree,standard,completed,100,100,100
114,female,group E,bachelor's degree,standard,completed,99,100,100

In [41]:
#sort values in descending order in a column in csv file
df.sort_values('writing score', ascending=False)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
179,female,group D,some high school,standard,completed,97,100,100
114,female,group E,bachelor's degree,standard,completed,99,100,100
903,female,group D,bachelor's degree,free/reduced,completed,93,100,100
403,female,group D,high school,standard,completed,88,99,100
458,female,group E,bachelor's degree,standard,none,100,100,100
...,...,...,...,...,...,...,...,...
980,female,group B,high school,free/reduced,none,8,24,23
76,male,group E,some high school,standard,none,30,26,22
327,male,group A,some college,free/reduced,none,28,23,19
596,male,group B,high school,free/reduced,none,30,24,15
59,female,group C,some high school,free/reduced,none,0,17,10

In [42]:
#sort values in ascending and descending order in multiple columns in csv file
df.sort_values(['math score', 'reading score', 'writing score'], ascending = [1, 1, 0])

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
59,female,group C,some high school,free/reduced,none,0,17,10
980,female,group B,high school,free/reduced,none,8,24,23
17,female,group B,some high school,free/reduced,none,18,32,28
787,female,group B,some college,standard,none,19,38,32
145,female,group C,some college,free/reduced,none,22,39,33
...,...,...,...,...,...,...,...,...
625,male,group D,some college,standard,completed,100,97,99
458,female,group E,bachelor's degree,standard,none,100,100,100
916,male,group E,bachelor's degree,standard,completed,100,100,100
962,female,group E,associate's degree,standard,none,100,100,100
149,male,group E,associate's degree,free/reduced,completed,100,100,93

### Make changes to the data

In [45]:
#summing up data in new column in csv file
df['total score'] = df['math score'] + df['reading score'] + df['writing score']
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total score
0,female,group B,bachelor's degree,standard,none,72,72,74,218
1,female,group C,some college,standard,completed,69,90,88,247
2,female,group B,master's degree,standard,none,90,95,93,278
3,male,group A,associate's degree,free/reduced,none,47,57,44,148
4,male,group C,some college,standard,none,76,78,75,229
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,282
996,male,group C,high school,free/reduced,none,62,55,55,172
997,female,group C,high school,free/reduced,completed,59,71,65,195
998,female,group D,some college,standard,completed,68,78,77,223
999,female,group D,some college,free/reduced,none,77,86,86,249

In [47]:
#dropping a column in csv file
df = df.drop(columns = ['total score'])
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [69]:
#remove duplicated columns in csv file
df = df.loc[:, ~df.columns.duplicated()]
df

,gender,race/ethnicity,parental level of education,lunch,math score,total score
0,female,group B,bachelor's degree,standard,72,216
1,female,group C,some college,standard,69,207
2,female,group B,master's degree,standard,90,270
3,male,group A,associate's degree,free/reduced,47,141
4,male,group C,some college,standard,76,228
...,...,...,...,...,...,...
995,female,group E,master's degree,standard,88,264
996,male,group C,high school,free/reduced,62,186
997,female,group C,high school,free/reduced,59,177
998,female,group D,some college,standard,68,204
999,female,group D,some college,free/reduced,77,231

In [71]:
#saving modified csv file
df.to_csv('modified proj1.csv', index=False)

### Filtering Data

In [73]:
df = pd.read_csv('StudentsPerformance.csv')
df.head(5)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [74]:
df['total score'] = df['math score'] + df['reading score'] + df['writing score']
df.head(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total score
0,female,group B,bachelor's degree,standard,none,72,72,74,218
1,female,group C,some college,standard,completed,69,90,88,247
2,female,group B,master's degree,standard,none,90,95,93,278
3,male,group A,associate's degree,free/reduced,none,47,57,44,148
4,male,group C,some college,standard,none,76,78,75,229
5,female,group B,associate's degree,standard,none,71,83,78,232
6,female,group B,some college,standard,completed,88,95,92,275
7,male,group B,some college,free/reduced,none,40,43,39,122
8,male,group D,high school,free/reduced,completed,64,64,67,195
9,female,group B,high school,free/reduced,none,38,60,50,148

In [79]:
cols_set1 = ['gender', 'race/ethnicity', 'parental level of education', 'lunch', 'test preparation course']
cols_set2 = ['math score', 'reading score', 'writing score']
df = df[cols_set1 + ['total score'] + cols_set2]

df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,total score,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,218,72,72,74
1,female,group C,some college,standard,completed,247,69,90,88
2,female,group B,master's degree,standard,none,278,90,95,93
3,male,group A,associate's degree,free/reduced,none,148,47,57,44
4,male,group C,some college,standard,none,229,76,78,75
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,282,88,99,95
996,male,group C,high school,free/reduced,none,172,62,55,55
997,female,group C,high school,free/reduced,completed,195,59,71,65
998,female,group D,some college,standard,completed,223,68,78,77
999,female,group D,some college,free/reduced,none,249,77,86,86

In [80]:
#filter using specific data in csv file 
df.loc[df['parental level of education'] == "bachelor's degree"]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,total score,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,218,72,72,74
24,male,group D,bachelor's degree,free/reduced,completed,225,74,71,80
27,female,group C,bachelor's degree,standard,none,211,67,69,75
60,male,group E,bachelor's degree,free/reduced,completed,225,79,74,72
77,male,group A,bachelor's degree,standard,completed,239,80,78,81
...,...,...,...,...,...,...,...,...,...
916,male,group E,bachelor's degree,standard,completed,300,100,100,100
933,male,group C,bachelor's degree,free/reduced,completed,219,70,75,74
969,female,group B,bachelor's degree,standard,none,239,75,84,80
970,female,group D,bachelor's degree,standard,none,289,89,100,100
993,female,group D,bachelor's degree,free/reduced,none,208,62,72,74

In [82]:
#filter using multiple data in csv file
df.loc[(df['parental level of education'] == "bachelor's degree") & (df['test preparation course'] == "completed")]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,total score,math score,reading score,writing score
24,male,group D,bachelor's degree,free/reduced,completed,225,74,71,80
60,male,group E,bachelor's degree,free/reduced,completed,225,79,74,72
77,male,group A,bachelor's degree,standard,completed,239,80,78,81
101,male,group D,bachelor's degree,standard,completed,216,68,74,74
114,female,group E,bachelor's degree,standard,completed,299,99,100,100
120,female,group C,bachelor's degree,standard,completed,260,79,92,89
134,male,group D,bachelor's degree,free/reduced,completed,228,74,79,75
148,female,group D,bachelor's degree,standard,completed,224,68,75,81
165,female,group C,bachelor's degree,standard,completed,296,96,100,100
174,female,group C,bachelor's degree,free/reduced,completed,148,43,51,54
234,male,group C,bachelor's degree,standard,completed,249,83,82,84
312,male,group D,bachelor's degree,standard,completed,196,67,61,68
314,female,group C,bachelor's degree,standard,completed,198,59,64,75
347,female,group C,bachelor's degree,standard,completed,266,77,94,95
365,male,group A,bachelor's degree,free/reduced,completed,167,49,58,60
414,female,group C,bachelor's degree,free/reduced,completed,202,51,72,79
416,male,group C,bachelor's degree,standard,completed,213,71,74,68
464,male,group A,bachelor's degree,standard,completed,195,75,58,62
475,female,group D,bachelor's degree,standard,completed,230,71,76,83
476,male,group E,bachelor's degree,standard,completed,204,76,62,66
535,female,group C,bachelor's degree,free/reduced,completed,232,66,83,83
538,male,group E,bachelor's degree,standard,completed,222,85,66,71
551,male,group B,bachelor's degree,free/reduced,completed,265,87,90,88
562,male,group C,bachelor's degree,standard,completed,278,96,90,92
566,female,group E,bachelor's degree,free/reduced,completed,292,92,100,100
594,female,group C,bachelor's degree,standard,completed,291,92,100,99
595,female,group C,bachelor's degree,standard,completed,207,56,79,72
612,male,group C,bachelor's degree,standard,completed,275,94,90,91
632,female,group B,bachelor's degree,standard,completed,221,66,74,81
645,female,group B,bachelor's degree,standard,completed,227,65,81,81
692,female,group C,bachelor's degree,free/reduced,completed,221,66,74,81
700,female,group E,bachelor's degree,standard,completed,242,79,81,82
702,male,group A,bachelor's degree,standard,completed,258,87,84,87
757,male,group E,bachelor's degree,free/reduced,completed,210,70,68,72
784,male,group C,bachelor's degree,standard,completed,251,91,81,79
817,male,group D,bachelor's degree,free/reduced,completed,207,61,70,76
831,female,group C,bachelor's degree,free/reduced,completed,249,74,86,89
862,male,group D,bachelor's degree,free/reduced,completed,119,39,42,38
880,male,group C,bachelor's degree,standard,completed,193,63,64,66
881,female,group E,bachelor's degree,standard,completed,211,71,70,70
903,female,group D,bachelor's degree,free/reduced,completed,293,93,100,100
909,male,group E,bachelor's degree,standard,completed,204,70,64,70
912,female,group C,bachelor's degree,standard,completed,179,52,61,66
913,female,group C,bachelor's degree,free/reduced,completed,175,47,62,66
916,male,group E,bachelor's degree,standard,completed,300,100,100,100
933,male,group C,bachelor's degree,free/reduced,completed,219,70,75,74

In [85]:
#specify limits for data in csv file 
new_df = df.loc[(df['parental level of education'] == "bachelor's degree") & (df['test preparation course'] == "completed") & (df['total score'] >= 220)]
new_df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,total score,math score,reading score,writing score
24,male,group D,bachelor's degree,free/reduced,completed,225,74,71,80
60,male,group E,bachelor's degree,free/reduced,completed,225,79,74,72
77,male,group A,bachelor's degree,standard,completed,239,80,78,81
114,female,group E,bachelor's degree,standard,completed,299,99,100,100
120,female,group C,bachelor's degree,standard,completed,260,79,92,89
134,male,group D,bachelor's degree,free/reduced,completed,228,74,79,75
148,female,group D,bachelor's degree,standard,completed,224,68,75,81
165,female,group C,bachelor's degree,standard,completed,296,96,100,100
234,male,group C,bachelor's degree,standard,completed,249,83,82,84
347,female,group C,bachelor's degree,standard,completed,266,77,94,95
475,female,group D,bachelor's degree,standard,completed,230,71,76,83
535,female,group C,bachelor's degree,free/reduced,completed,232,66,83,83
538,male,group E,bachelor's degree,standard,completed,222,85,66,71
551,male,group B,bachelor's degree,free/reduced,completed,265,87,90,88
562,male,group C,bachelor's degree,standard,completed,278,96,90,92
566,female,group E,bachelor's degree,free/reduced,completed,292,92,100,100
594,female,group C,bachelor's degree,standard,completed,291,92,100,99
612,male,group C,bachelor's degree,standard,completed,275,94,90,91
632,female,group B,bachelor's degree,standard,completed,221,66,74,81
645,female,group B,bachelor's degree,standard,completed,227,65,81,81
692,female,group C,bachelor's degree,free/reduced,completed,221,66,74,81
700,female,group E,bachelor's degree,standard,completed,242,79,81,82
702,male,group A,bachelor's degree,standard,completed,258,87,84,87
784,male,group C,bachelor's degree,standard,completed,251,91,81,79
831,female,group C,bachelor's degree,free/reduced,completed,249,74,86,89
903,female,group D,bachelor's degree,free/reduced,completed,293,93,100,100
916,male,group E,bachelor's degree,standard,completed,300,100,100,100

In [98]:
#reset index in csv file
new_df = new_df.reset_index()
new_df

,level_0,index,gender,race/ethnicity,parental level of education,lunch,test preparation course,total score,math score,reading score,writing score
0,0,24,male,group D,bachelor's degree,free/reduced,completed,225,74,71,80
1,1,60,male,group E,bachelor's degree,free/reduced,completed,225,79,74,72
2,2,77,male,group A,bachelor's degree,standard,completed,239,80,78,81
3,3,114,female,group E,bachelor's degree,standard,completed,299,99,100,100
4,4,120,female,group C,bachelor's degree,standard,completed,260,79,92,89
5,5,134,male,group D,bachelor's degree,free/reduced,completed,228,74,79,75
6,6,148,female,group D,bachelor's degree,standard,completed,224,68,75,81
7,7,165,female,group C,bachelor's degree,standard,completed,296,96,100,100
8,8,234,male,group C,bachelor's degree,standard,completed,249,83,82,84
9,9,347,female,group C,bachelor's degree,standard,completed,266,77,94,95
10,10,475,female,group D,bachelor's degree,standard,completed,230,71,76,83
11,11,535,female,group C,bachelor's degree,free/reduced,completed,232,66,83,83
12,12,538,male,group E,bachelor's degree,standard,completed,222,85,66,71
13,13,551,male,group B,bachelor's degree,free/reduced,completed,265,87,90,88
14,14,562,male,group C,bachelor's degree,standard,completed,278,96,90,92
15,15,566,female,group E,bachelor's degree,free/reduced,completed,292,92,100,100
16,16,594,female,group C,bachelor's degree,standard,completed,291,92,100,99
17,17,612,male,group C,bachelor's degree,standard,completed,275,94,90,91
18,18,632,female,group B,bachelor's degree,standard,completed,221,66,74,81
19,19,645,female,group B,bachelor's degree,standard,completed,227,65,81,81
20,20,692,female,group C,bachelor's degree,free/reduced,completed,221,66,74,81
21,21,700,female,group E,bachelor's degree,standard,completed,242,79,81,82
22,22,702,male,group A,bachelor's degree,standard,completed,258,87,84,87
23,23,784,male,group C,bachelor's degree,standard,completed,251,91,81,79
24,24,831,female,group C,bachelor's degree,free/reduced,completed,249,74,86,89
25,25,903,female,group D,bachelor's degree,free/reduced,completed,293,93,100,100
26,26,916,male,group E,bachelor's degree,standard,completed,300,100,100,100

In [99]:
new_df = new_df.drop(['level_0'], axis=1)
new_df

,index,gender,race/ethnicity,parental level of education,lunch,test preparation course,total score,math score,reading score,writing score
0,24,male,group D,bachelor's degree,free/reduced,completed,225,74,71,80
1,60,male,group E,bachelor's degree,free/reduced,completed,225,79,74,72
2,77,male,group A,bachelor's degree,standard,completed,239,80,78,81
3,114,female,group E,bachelor's degree,standard,completed,299,99,100,100
4,120,female,group C,bachelor's degree,standard,completed,260,79,92,89
5,134,male,group D,bachelor's degree,free/reduced,completed,228,74,79,75
6,148,female,group D,bachelor's degree,standard,completed,224,68,75,81
7,165,female,group C,bachelor's degree,standard,completed,296,96,100,100
8,234,male,group C,bachelor's degree,standard,completed,249,83,82,84
9,347,female,group C,bachelor's degree,standard,completed,266,77,94,95
10,475,female,group D,bachelor's degree,standard,completed,230,71,76,83
11,535,female,group C,bachelor's degree,free/reduced,completed,232,66,83,83
12,538,male,group E,bachelor's degree,standard,completed,222,85,66,71
13,551,male,group B,bachelor's degree,free/reduced,completed,265,87,90,88
14,562,male,group C,bachelor's degree,standard,completed,278,96,90,92
15,566,female,group E,bachelor's degree,free/reduced,completed,292,92,100,100
16,594,female,group C,bachelor's degree,standard,completed,291,92,100,99
17,612,male,group C,bachelor's degree,standard,completed,275,94,90,91
18,632,female,group B,bachelor's degree,standard,completed,221,66,74,81
19,645,female,group B,bachelor's degree,standard,completed,227,65,81,81
20,692,female,group C,bachelor's degree,free/reduced,completed,221,66,74,81
21,700,female,group E,bachelor's degree,standard,completed,242,79,81,82
22,702,male,group A,bachelor's degree,standard,completed,258,87,84,87
23,784,male,group C,bachelor's degree,standard,completed,251,91,81,79
24,831,female,group C,bachelor's degree,free/reduced,completed,249,74,86,89
25,903,female,group D,bachelor's degree,free/reduced,completed,293,93,100,100
26,916,male,group E,bachelor's degree,standard,completed,300,100,100,100

In [102]:
#filter using substring in csv file
new_df = new_df.loc[new_df['lunch'].str.contains('reduced')]
new_df

,index,gender,race/ethnicity,parental level of education,lunch,test preparation course,total score,math score,reading score,writing score
0,24,male,group D,bachelor's degree,free/reduced,completed,225,74,71,80
1,60,male,group E,bachelor's degree,free/reduced,completed,225,79,74,72
5,134,male,group D,bachelor's degree,free/reduced,completed,228,74,79,75
11,535,female,group C,bachelor's degree,free/reduced,completed,232,66,83,83
13,551,male,group B,bachelor's degree,free/reduced,completed,265,87,90,88
15,566,female,group E,bachelor's degree,free/reduced,completed,292,92,100,100
20,692,female,group C,bachelor's degree,free/reduced,completed,221,66,74,81
24,831,female,group C,bachelor's degree,free/reduced,completed,249,74,86,89
25,903,female,group D,bachelor's degree,free/reduced,completed,293,93,100,100

In [104]:
#use regex to further filter in csv file
import re
new_df = new_df.loc[new_df['race/ethnicity'].str.contains("C|D", flags = re.I, regex=True)]
new_df

,index,gender,race/ethnicity,parental level of education,lunch,test preparation course,total score,math score,reading score,writing score
0,24,male,group D,bachelor's degree,free/reduced,completed,225,74,71,80
5,134,male,group D,bachelor's degree,free/reduced,completed,228,74,79,75
11,535,female,group C,bachelor's degree,free/reduced,completed,232,66,83,83
20,692,female,group C,bachelor's degree,free/reduced,completed,221,66,74,81
24,831,female,group C,bachelor's degree,free/reduced,completed,249,74,86,89
25,903,female,group D,bachelor's degree,free/reduced,completed,293,93,100,100

### Making Conditional Changes

In [107]:
#change specific entry in csv file
df.loc[df["parental level of education"] == "bachelor's degree", "parental level of education"] = "Bachelor's"
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,total score,math score,reading score,writing score
0,female,group B,Bachelor's,standard,none,218,72,72,74
1,female,group C,some college,standard,completed,247,69,90,88
2,female,group B,master's degree,standard,none,278,90,95,93
3,male,group A,associate's degree,free/reduced,none,148,47,57,44
4,male,group C,some college,standard,none,229,76,78,75
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,282,88,99,95
996,male,group C,high school,free/reduced,none,172,62,55,55
997,female,group C,high school,free/reduced,completed,195,59,71,65
998,female,group D,some college,standard,completed,223,68,78,77
999,female,group D,some college,free/reduced,none,249,77,86,86

In [108]:
#using condition to change values in csv file
df.loc[df['total score'] > 220, ['test preparation course']] = 'GOOD WORK'
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,total score,math score,reading score,writing score
0,female,group B,Bachelor's,standard,none,218,72,72,74
1,female,group C,some college,standard,GOOD WORK,247,69,90,88
2,female,group B,master's degree,standard,GOOD WORK,278,90,95,93
3,male,group A,associate's degree,free/reduced,none,148,47,57,44
4,male,group C,some college,standard,GOOD WORK,229,76,78,75
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,GOOD WORK,282,88,99,95
996,male,group C,high school,free/reduced,none,172,62,55,55
997,female,group C,high school,free/reduced,completed,195,59,71,65
998,female,group D,some college,standard,GOOD WORK,223,68,78,77
999,female,group D,some college,free/reduced,GOOD WORK,249,77,86,86

In [110]:
#using condition to change values across multiple columns in csv file
df.loc[df['total score'] > 220, ['test preparation course', 'lunch']] = ['GOOD WORK', 'SPECIAL']
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,total score,math score,reading score,writing score
0,female,group B,Bachelor's,standard,none,218,72,72,74
1,female,group C,some college,SPECIAL,GOOD WORK,247,69,90,88
2,female,group B,master's degree,SPECIAL,GOOD WORK,278,90,95,93
3,male,group A,associate's degree,free/reduced,none,148,47,57,44
4,male,group C,some college,SPECIAL,GOOD WORK,229,76,78,75
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,SPECIAL,GOOD WORK,282,88,99,95
996,male,group C,high school,free/reduced,none,172,62,55,55
997,female,group C,high school,free/reduced,completed,195,59,71,65
998,female,group D,some college,SPECIAL,GOOD WORK,223,68,78,77
999,female,group D,some college,SPECIAL,GOOD WORK,249,77,86,86

### Statistics

In [115]:
#find mean data across unique column values in csv file
df.groupby(['gender']).mean().sort_values('total score', ascending=True)

        total score  math score  reading score  writing score
gender
male     197.512448   68.728216      65.473029      63.311203
female   208.708494   63.633205      72.608108      72.467181

In [116]:
#find mean data across unique column values in csv file 
df.groupby(['race/ethnicity']).mean().sort_values('total score', ascending=False)

                total score  math score  reading score  writing score
race/ethnicity
group E          218.257143   73.821429      73.028571      71.407143
group D          207.538168   67.362595      70.030534      70.145038
group C          201.394984   64.463950      69.103448      67.827586
group B          196.405263   63.452632      67.352632      65.600000
group A          188.977528   61.629213      64.674157      62.674157

In [118]:
#count specific values in columns in csv file
df['count'] = 1
df.groupby(['race/ethnicity']).count()['count']

race/ethnicity
group A     89
group B    190
group C    319
group D    262
group E    140
Name: count, dtype: int64